version: '3.8'
services:
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: dayvinchik
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dayvinchik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
volumes:
  postgres_data:
